/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HHostSlugRouteImport } from './routes/h.$hostSlug'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedMyEventsRouteImport } from './routes/_authenticated/my-events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHostsNewRouteImport } from './routes/_authenticated/hosts.new'
import { Route as AuthenticatedHostsHostSlugEditRouteImport } from './routes/_authenticated/hosts.$hostSlug.edit'
import { Route as AuthenticatedEventsEventIdEditRouteImport } from './routes/_authenticated/events.$eventId.edit'
import { Route as AuthenticatedHostsHostSlugEventsNewRouteImport } from './routes/_authenticated/hosts.$hostSlug.events.new'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HHostSlugRoute = HHostSlugRouteImport.update({
  id: '/h/$hostSlug',
  path: '/h/$hostSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyEventsRoute = AuthenticatedMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsNewRoute = AuthenticatedHostsNewRouteImport.update({
  id: '/hosts/new',
  path: '/hosts/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostsHostSlugEditRoute =
  AuthenticatedHostsHostSlugEditRouteImport.update({
    id: '/hosts/$hostSlug/edit',
    path: '/hosts/$hostSlug/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsEventIdEditRoute =
  AuthenticatedEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostsHostSlugEventsNewRoute =
  AuthenticatedHostsHostSlugEventsNewRouteImport.update({
    id: '/hosts/$hostSlug/events/new',
    path: '/hosts/$hostSlug/events/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/h/$hostSlug': typeof HHostSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/hosts/new': typeof AuthenticatedHostsNewRoute
  '/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/hosts/$hostSlug/edit': typeof AuthenticatedHostsHostSlugEditRoute
  '/hosts/$hostSlug/events/new': typeof AuthenticatedHostsHostSlugEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/h/$hostSlug': typeof HHostSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/hosts/new': typeof AuthenticatedHostsNewRoute
  '/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/hosts/$hostSlug/edit': typeof AuthenticatedHostsHostSlugEditRoute
  '/hosts/$hostSlug/events/new': typeof AuthenticatedHostsHostSlugEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-events': typeof AuthenticatedMyEventsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/h/$hostSlug': typeof HHostSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/hosts/new': typeof AuthenticatedHostsNewRoute
  '/_authenticated/events/$eventId/edit': typeof AuthenticatedEventsEventIdEditRoute
  '/_authenticated/hosts/$hostSlug/edit': typeof AuthenticatedHostsHostSlugEditRoute
  '/_authenticated/hosts/$hostSlug/events/new': typeof AuthenticatedHostsHostSlugEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/dashboard'
    | '/my-events'
    | '/tickets'
    | '/events/$eventId'
    | '/h/$hostSlug'
    | '/invite/$token'
    | '/hosts/new'
    | '/events/$eventId/edit'
    | '/hosts/$hostSlug/edit'
    | '/hosts/$hostSlug/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/dashboard'
    | '/my-events'
    | '/tickets'
    | '/events/$eventId'
    | '/h/$hostSlug'
    | '/invite/$token'
    | '/hosts/new'
    | '/events/$eventId/edit'
    | '/hosts/$hostSlug/edit'
    | '/hosts/$hostSlug/events/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-events'
    | '/_authenticated/tickets'
    | '/events/$eventId'
    | '/h/$hostSlug'
    | '/invite/$token'
    | '/_authenticated/hosts/new'
    | '/_authenticated/events/$eventId/edit'
    | '/_authenticated/hosts/$hostSlug/edit'
    | '/_authenticated/hosts/$hostSlug/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  HHostSlugRoute: typeof HHostSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$hostSlug': {
      id: '/h/$hostSlug'
      path: '/h/$hostSlug'
      fullPath: '/h/$hostSlug'
      preLoaderRoute: typeof HHostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-events': {
      id: '/_authenticated/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof AuthenticatedMyEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/new': {
      id: '/_authenticated/hosts/new'
      path: '/hosts/new'
      fullPath: '/hosts/new'
      preLoaderRoute: typeof AuthenticatedHostsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/$hostSlug/edit': {
      id: '/_authenticated/hosts/$hostSlug/edit'
      path: '/hosts/$hostSlug/edit'
      fullPath: '/hosts/$hostSlug/edit'
      preLoaderRoute: typeof AuthenticatedHostsHostSlugEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId/edit': {
      id: '/_authenticated/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof AuthenticatedEventsEventIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosts/$hostSlug/events/new': {
      id: '/_authenticated/hosts/$hostSlug/events/new'
      path: '/hosts/$hostSlug/events/new'
      fullPath: '/hosts/$hostSlug/events/new'
      preLoaderRoute: typeof AuthenticatedHostsHostSlugEventsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyEventsRoute: typeof AuthenticatedMyEventsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedHostsNewRoute: typeof AuthenticatedHostsNewRoute
  AuthenticatedEventsEventIdEditRoute: typeof AuthenticatedEventsEventIdEditRoute
  AuthenticatedHostsHostSlugEditRoute: typeof AuthenticatedHostsHostSlugEditRoute
  AuthenticatedHostsHostSlugEventsNewRoute: typeof AuthenticatedHostsHostSlugEventsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyEventsRoute: AuthenticatedMyEventsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedHostsNewRoute: AuthenticatedHostsNewRoute,
  AuthenticatedEventsEventIdEditRoute: AuthenticatedEventsEventIdEditRoute,
  AuthenticatedHostsHostSlugEditRoute: AuthenticatedHostsHostSlugEditRoute,
  AuthenticatedHostsHostSlugEventsNewRoute:
    AuthenticatedHostsHostSlugEventsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  HHostSlugRoute: HHostSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
